### PR TITLE
FIXED: Duplicate Coverage ID and Subscriber ID Entries in check coverage eligibility Dropdown

### LINKED ISSUE #9: Duplicate Coverage ID and Subscriber ID Entries in check coverage eligibility Dropdown
Describe the bug
The dropdown displays duplicate coverage records where the same Coverage ID and Subscriber ID appear multiple times

### PR DESCRIPTION
**Pull request by modamaan**
[Issue Link](https://github.com/ohcnetwork/care_fe/issues/11256)
#9
- Fixes #9  

https://github.com/user-attachments/assets/be6efa25-f6dc-4ab0-abb7-b6991fc66c35

### CODE REVIEW

**Comment by modamaan** [comment]
@khavinshankar  can you please check the PR

File: src/components/encounter-tabs/Claims.tsx [hunk 1]
```diff
@@ -480,6 +480,19 @@ const ManageCoverages: FC<ManageCoveragesProps> = ({ patientId }) => {
...
   function onSubmit(values: z.infer<typeof coverageFormSchema>) {
+    const isDuplicate = coverages?.results.some(
+      (coverage) =>
+        coverage.identifier === values.identifier &&
+        coverage.subscriber_id === values.subscriber_id
+    );
+
+    if (isDuplicate) {
+      toast.error(
+        "This Coverage ID and Subscriber ID combination already exists. Please enter a unique combination."
```
Comment (rithviknishad) [inline src/components/encounter-tabs/Claims.tsx:491]: i18n?

**Review by rithviknishad — CHANGES_REQUESTED** [review]

**Comment by rithviknishad** [comment]
Please link the issue in the PR with closing tags!

File: src/components/encounter-tabs/Claims.tsx (hunk 1 above)
Comment (modamaan) [reply src/components/encounter-tabs/Claims.tsx]: updated

**Comment by modamaan** [comment]
@rithviknishad @bodhish can you please check the updates

**Review by khavinshankar — APPROVED** [review]

**Comment by khavinshankar** [comment]
@modamaan just a headsup while linking the issue, just add it like `Resolves #issue_number` or anyother respective keywords (https://docs.github.com/en/get-started/writing-on-github/working-with-advanced-formatting/using-keywords-in-issues-and-pull-requests).
